import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    gap: 25,
    paddingTop: 10,
    marginBottom: 40,
  },
  settingContainer: {
    gap: 12,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: "#6b829e",
    letterSpacing: 1,
  },
  chipRow: {
    flexDirection: "row",
    gap: 12,
  },
  groupChip: {
    flex: 1,
    height: 70,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  timerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  timerChip: {
    width: "48%",
    height: 50,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  langChip: {
    flex: 1,
    height: 60,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  langInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  flagText: {
    fontSize: 22,
  },
  chipText: {
    fontWeight: "900",
    fontSize: 18,
    color: "#6b829e",
  },
  stepperPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 18,
    padding: 8,
    width: "100%",
  },
  stepperBtn: {
    width: 50,
    height: 50,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  pointsText: {
    fontSize: 32,
    fontWeight: "900",
    color: "#FFF",
  },
  playButton: {
    flexDirection: "row",
    height: 65,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  playButtonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 2,
  },
  togglePill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 12,
    width: "100%",
    borderWidth: 2,
    borderColor: "transparent",
  },
});
