import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  centerContent: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    top: 20,
  },
  headerContainer: {
    alignItems: "center",
    marginTop: 40,
  },
  teamTitle: {
    fontSize: 25,
    fontWeight: "900",
    color: "#e74c3c",
    letterSpacing: 2,
    marginBottom: 10,
  },
  mainTitle: {
    fontSize: 45,
    fontWeight: "900",
    height: 40,
    textAlignVertical: "center",
    color: "#fff",
    letterSpacing: -1,
  },
  scoreboardCard: {
    width: "90%",
    backgroundColor: "#1e1e1e",
    borderRadius: 20,
    padding: 24,
    marginTop: 30,
    borderWidth: 1,
    borderColor: "#333",
  },
  scoreboardHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  scoreboardContent: {
    maxHeight: 125,
  },
  scoreboardLabel: {
    fontSize: 16,
    fontWeight: "800",
    color: "#6b829e",
    letterSpacing: 1,
  },
  targetLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: "#e74c3c",
  },
  teamRow: {
    marginBottom: 16,
  },
  teamRowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  teamNameText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#888",
  },
  teamScoreText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#dda800",
  },
  activeTeamText: {
    color: "#fff",
  },
  activeScoreText: {
    color: "#e74c3c",
  },
  progressBarBackground: {
    height: 8,
    backgroundColor: "#2c3e50",
    borderRadius: 4,
    width: "100%",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#6b829e",
    borderRadius: 4,
  },
  activeProgressBarFill: {
    backgroundColor: "#e74c3c",
  },
  middleActionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
  },
  pulseGlow: {
    width: 260,
    height: 260,
    borderRadius: 140,
    backgroundColor: "rgba(231, 76, 60, 0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  actionCircleButton: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#e74c3c",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#e74c3c",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 10,
  },
  actionInnerCircle: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  actionButtonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "900",
    marginTop: 10,
    letterSpacing: -1,
  },
});
