import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 25,
    paddingVertical: 40,
    justifyContent: "space-between",
    alignItems: "center",
  },
  header: {
    alignItems: "center",
    marginTop: 20,
  },
  trophyContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  gameOverText: {
    fontSize: 16,
    letterSpacing: 2,
    fontWeight: "700",
    color: "#D32F2F",
    marginBottom: 5,
  },
  winnerNameContainer: {
    alignItems: "center",
  },
  winnerName: {
    fontSize: 48,
    fontWeight: "900",
    textAlign: "center",
    height: 50,
    textAlignVertical: "center",
  },
  winsText: {
    fontSize: 48,
    fontWeight: "900",
    height: 40,
    textAlignVertical: "center",
  },
  card: {
    width: "100%",
    borderRadius: 25,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    marginVertical: 30,
  },
  scoreboardContent: {
    maxHeight: 170,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 15,
  },
  divider: {
    height: 1,
    width: "100%",
    marginBottom: 20,
  },
  scoreRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 18,
    marginBottom: 12,
  },
  rowLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  rank: {
    fontSize: 18,
    fontWeight: "900",
    marginRight: 12,
    opacity: 0.5,
  },
  groupName: {
    fontSize: 18,
    fontWeight: "700",
  },
  rowRight: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  scoreValue: {
    fontSize: 24,
    fontWeight: "900",
    marginRight: 4,
  },
  ptsLabel: {
    fontSize: 12,
    fontWeight: "700",
    opacity: 0.6,
  },
  whiteText: {
    color: "#FFFFFF",
    opacity: 1,
  },
  playAgainButton: {
    flexDirection: "row",
    width: "100%",
    height: 60,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  playAgainText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 1,
  },
});
